### ISSUE TITLE
Crash when using Server Spawn portals to switch between servers

### ISSUE THREAD

**Issue by betorob** [Tekkify/Tekkify#13]
Here's a truncated copy of the crash report.  If you need more you know where to find me.

---- Minecraft Crash Report ----
// Oops.

Time: 1/11/15 2:23 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at com.carpentersblocks.renderer.BlockHandlerBase.getIcon(BlockHandlerBase.java:531)
	at com.carpentersblocks.renderer.BlockHandlerBase.renderMultiTexturedSide(BlockHandlerBase.java:566)
	at com.carpentersblocks.renderer.BlockHandlerBase.delegateSideRender(BlockHandlerBase.java:612)
	at com.carpentersblocks.renderer.BlockHandlerBase.renderBlock(BlockHandlerBase.java:854)
	at com.carpentersblocks.renderer.BlockHandlerBase.renderBlockWithRotation(BlockHandlerBase.java:161)
	at com.carpentersblocks.renderer.BlockHandlerCarpentersGarageDoor.renderTypeDefault(BlockHandlerCarpentersGarageDoor.java:116)
	at com.carpentersblocks.renderer.BlockHandlerCarpentersGarageDoor.renderCarpentersBlock(BlockHandlerCarpentersGarageDoor.java:48)
	at com.carpentersblocks.renderer.BlockHandlerBase.renderWorldBlock(BlockHandlerBase.java:126)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

--

**Comment by Nentify** [comment]
thanks

**Comment by Nentify** [comment]
Same issue as #16
