### ISSUE TITLE
Chisel Present Box throwing exception in server log when Ender IO Conduit attempts to push entity into Present Box

### ISSUE THREAD

**Issue by the-ible** [Tekkify/Tekkify#28]
[22:15:36] [Server thread/ERROR] [FML/]: A TileEntity tile.present.present(com.cricketcraft.chisel.block.tilee
ntity.TileEntityPresent) located @ 1241,61,821 has thrown an exception during creation, it cannot be created.
Report this to the mod author
java.lang.InstantiationException: com.cricketcraft.chisel.block.tileentity.TileEntityPresent
        at java.lang.Class.newInstance(Class.java:364) ~[?:1.7.0_65]
        at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:108) [aor.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:525) [aqk.cla
ss:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvi
der.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvi
der.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [Async
hronousExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [As
ynchronousExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOEx
ecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:739) [ahb.class:?]
        at net.minecraft.world.World.func_147438_o(World.java:3115) [ahb.class:?]
        at crazypants.enderio.machine.capbank.network.NetworkUtil.getNeigbours(NetworkUtil.java:43) [NetworkUt
il.class:?]
        at crazypants.enderio.machine.capbank.network.NetworkUtil.getNeigbours(NetworkUtil.java:36) [NetworkUt
il.class:?]
        at crazypants.enderio.machine.capbank.network.NetworkUtil.ensureValidNetwork(NetworkUtil.java:22) [Net
workUtil.class:?]
        at crazypants.enderio.machine.capbank.TileCapBank.updateNetwork(TileCapBank.java:216) [TileCapBank.cla
ss:?]
        at crazypants.enderio.machine.capbank.TileCapBank.func_145845_h(TileCapBank.java:180) [TileCapBank.cla
ss:?]
        at net.minecraft.world.World.func_72939_s(World.java:2491) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) [MinecraftServer.class:
?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:
?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

I went to the location specified (1241, 61, 821) and found a Chisel Present Box connected to machinery via and Ender IO Conduit. I removed the Present Box and left a sign indicating the Present Box should not be connected to Ender IO Conduit.

**Comment by Nentify** [comment]
We'll have to remove these on a case-by-case basis for now (if it still occurs, both mods have been updated)
